// legacy/game/BottomActionBar.tsx
import React from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Flame, Map, Scroll, Package, ShoppingBag, Users } from 'lucide-react';

const quickActions = [
  { key: 'cultivation', label: '修炼', icon: <Flame size={20} />, path: '/cultivation', color: '#f59e0b' },
  { key: 'explore', label: '探索', icon: <Map size={20} />, path: '/explore', color: '#4ade80' },
  { key: 'quests', label: '任务', icon: <Scroll size={20} />, path: '/quests', color: '#60a5fa' },
  { key: 'inventory', label: '背包', icon: <Package size={20} />, path: '/inventory', color: '#a78bfa' },
  { key: 'shop', label: '坊市', icon: <ShoppingBag size={20} />, path: '/shop', color: '#f87171' },
  { key: 'social', label: '社交', icon: <Users size={20} />, path: '/social', color: '#34d399' },
];

const BottomActionBar: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();

  return (
    <nav
      className="fixed bottom-0 left-0 right-0 z-30 lg:hidden flex items-center justify-around px-2 py-2"
      style={{
        background: 'linear-gradient(180deg, rgba(13,17,23,0.98) 0%, rgba(18,22,30,0.97) 100%)',
        borderTop: '1px solid var(--color-border-gold)',
        boxShadow: '0 -2px 20px rgba(0,0,0,0.5), 0 0 20px rgba(212, 168, 67, 0.05)',
        backdropFilter: 'blur(12px)',
      }}
    >
      {/* 顶部金色光带 */}
      <div
        className="absolute top-0 left-0 right-0 h-px"
        style={{
          background: 'linear-gradient(90deg, transparent, var(--color-gold), transparent)',
          boxShadow: '0 0 8px var(--color-gold)',
        }}
      />

      {quickActions.map((action) => {
        const isActive = location.pathname === action.path;
        return (
          <button
            key={action.key}
            onClick={() => navigate(action.path)}
            className="flex flex-col items-center gap-0.5 px-3 py-1.5 rounded-xl transition-all duration-200 relative group"
            style={{
              color: isActive ? action.color : 'var(--color-text-muted)',
              background: isActive ? `rgba(255,255,255,0.08)` : 'transparent',
              transform: isActive ? 'translateY(-2px)' : 'translateY(0)',
            }}
          >
            {/* 激活状态背景光效 */}
            {isActive && (
              <div
                className="absolute inset-0 rounded-xl"
                style={{
                  background: `radial-gradient(circle, ${action.color}15 0%, transparent 70%)`,
                  boxShadow: `0 0 12px ${action.color}30`,
                }}
              />
            )}

            {/* 悬停光效 */}
            <div
              className="absolute inset-0 rounded-xl opacity-0 group-hover:opacity-100 transition-opacity duration-200"
              style={{
                background: 'radial-gradient(circle, rgba(255,255,255,0.05) 0%, transparent 70%)',
              }}
            />

            <span 
              className={`transition-all duration-200 ${isActive ? 'scale-115' : 'group-hover:scale-110'}`}
              style={{
                filter: isActive ? `drop-shadow(0 0 6px ${action.color})` : 'none',
              }}
            >
              {action.icon}
            </span>
            <span className={`text-xs font-medium transition-all duration-200 ${isActive ? 'font-bold' : ''}`}>
              {action.label}
            </span>

            {/* 激活状态底部指示点 */}
            {isActive && (
              <div
                className="absolute -bottom-0.5 w-1 h-1 rounded-full"
                style={{
                  background: action.color,
                  boxShadow: `0 0 6px ${action.color}`,
                }}
              />
            )}
          </button>
        );
      })}
    </nav>
  );
};

export default BottomActionBar;

// src/components/game/BottomActionBar.vue
<template>
  <div
    class="fixed bottom-0 left-0 right-0 z-50 flex justify-center"
    style="background: linear-gradient(180deg, transparent 0%, rgba(13,17,23,0.95) 20%); paddingBottom: env(safe-area-inset-bottom)"
  >
    <div
      class="flex items-center gap-2 px-4 py-3 mx-4 rounded-full shadow-lg"
      :style="{
        background: 'rgba(22,27,34,0.95)',
        border: '1px solid var(--color-border-gold)',
        boxShadow: '0 -4px 30px rgba(0,0,0,0.5), 0 0 20px rgba(212,168,67,0.1)',
        backdropFilter: 'blur(12px)'
      }"
    >
      <button
        v-for="(action, index) in actions"
        :key="action.id"
        class="flex flex-col items-center justify-center p-2 rounded-full transition-all duration-200 min-w-[56px]"
        :class="[
          activeAction === action.id
            ? 'scale-110'
            : 'hover:scale-105'
        ]"
        :style="{
          background: activeAction === action.id
            ? `linear-gradient(145deg, rgba(212,168,67,0.2) 0%, rgba(212,168,67,0.1) 100%)`
            : 'transparent',
          boxShadow: activeAction === action.id ? '0 0 12px rgba(212,168,67,0.3)' : 'none'
        }"
        @click="handleAction(action)"
        @mouseenter="activeAction = action.id"
        @mouseleave="activeAction = null"
      >
        <component
          :is="action.icon"
          :size="action.size || 20"
          :style="{
            color: activeAction === action.id
              ? 'var(--color-gold)'
              : action.color || 'var(--color-text-secondary)',
            filter: activeAction === action.id
              ? `drop-shadow(0 0 6px ${action.color || 'var(--color-gold)'})`
              : 'none',
            transition: 'all 0.2s ease'
          }"
        />
        <span
          v-if="action.label"
          class="text-[10px] mt-1 font-medium"
          :style="{
            color: activeAction === action.id
              ? 'var(--color-gold)'
              : 'var(--color-text-secondary)'
          }"
        >
          {{ action.label }}
        </span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, markRaw } from 'vue'
import { Home, Compass, Sword, Users, Bell } from 'lucide-vue-next'

interface Action {
  id: string
  label?: string
  icon: any
  color?: string
  size?: number
  action?: () => void
}

defineProps<{
  actions?: Action[]
}>()

const activeAction = ref<string | null>(null)

const defaultActions: Action[] = [
  { id: 'home', label: '首页', icon: markRaw(Home), color: 'var(--color-jade)' },
  { id: 'explore', label: '探索', icon: markRaw(Compass), color: '#a78bfa' },
  { id: 'battle', label: '战斗', icon: markRaw(Sword), color: '#f87171' },
  { id: 'social', label: '社交', icon: markRaw(Users), color: '#60a5fa' },
  { id: 'notice', label: '公告', icon: markRaw(Bell), color: 'var(--color-gold)' },
]

const actions = ref<Action[]>(defaultActions)

const handleAction = (action: Action) => {
  if (action.action) {
    action.action()
  }
}
</script>
