// src/components/game/SideMenu.vue
<template>
  <div
    class="flex flex-col h-full"
    :style="{ background: 'linear-gradient(180deg, rgba(13,17,23,0.98) 0%, rgba(22,27,34,0.95) 100%)', borderRight: '1px solid var(--color-border-gold)' }"
  >
    <div class="p-4">
      <div class="flex items-center gap-3 mb-6">
        <div class="w-12 h-12 rounded-lg overflow-hidden border-2" style="borderColor: var(--color-border-gold); boxShadow: 0 0 20px rgba(212,168,67,0.3)">
          <img
            :src="avatar || '/images/avatar-placeholder.png'"
            alt="avatar"
            class="w-full h-full object-cover"
          />
        </div>
        <div>
          <h3 class="font-semibold" style="color: var(--color-text-primary)">{{ username }}</h3>
          <p class="text-xs" style="color: var(--color-text-muted)">等级 {{ level }} · {{ sect }}</p>
        </div>
      </div>

      <div class="space-y-1">
        <button
          v-for="item in menuItems"
          :key="item.path"
          class="w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-all duration-200"
          :class="[
            isActive(item.path)
              ? 'bg-[rgba(212,168,67,0.15)] border border-[rgba(212,168,67,0.3)]'
              : 'hover:bg-white/5'
          ]"
          @click="navigate(item.path)"
        >
          <component
            :is="item.icon"
            :size="20"
            :style="{ color: isActive(item.path) ? 'var(--color-gold)' : 'var(--color-text-secondary)' }"
          />
          <span
            class="font-medium"
            :style="{ color: isActive(item.path) ? 'var(--color-gold)' : 'var(--color-text-primary)' }"
          >
            {{ item.label }}
          </span>
          <span
            v-if="item.badge"
            class="ml-auto px-2 py-0.5 text-xs font-medium rounded-full"
            style="background: rgba(212,168,67,0.2); color: var(--color-gold)"
          >
            {{ item.badge }}
          </span>
        </button>
      </div>
    </div>

    <div class="mt-auto p-4" style="borderTop: 1px solid var(--color-border)">
      <div class="space-y-2">
        <div class="flex items-center justify-between text-xs" style="color: var(--color-text-muted)">
          <span>今日活跃</span>
          <span class="font-medium" style="color: var(--color-jade)">{{ activity }}/100</span>
        </div>
        <div class="h-1.5 rounded-full overflow-hidden" style="background: rgba(0,0,0,0.3)">
          <div
            class="h-full rounded-full transition-all duration-300"
            style="background: linear-gradient(90deg, var(--color-jade), var(--color-gold))"
            :style="{ width: `${activity}%` }"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  Home,
  User,
  Sparkles,
  Compass,
  Scroll,
  Package,
  ShoppingBag,
  Trophy,
  Users,
  Settings,
  Activity,
} from 'lucide-vue-next'

interface Props {
  username?: string
  level?: number
  sect?: string
  activity?: number
  avatar?: string
}

withDefaults(defineProps<Props>(), {
  username: '散修弟子',
  level: 1,
  sect: '无宗门',
  activity: 0,
  avatar: '',
})

const route = useRoute()
const router = useRouter()

const menuItems = [
  { label: '首页大厅', path: '/lobby', icon: Home },
  { label: '角色', path: '/character', icon: User },
  { label: '修炼', path: '/cultivation', icon: Sparkles },
  { label: '探索', path: '/explore', icon: Compass },
  { label: '任务', path: '/quests', icon: Scroll, badge: '3' },
  { label: '背包', path: '/inventory', icon: Package },
  { label: '商店', path: '/shop', icon: ShoppingBag },
  { label: '排行榜', path: '/ranking', icon: Trophy },
  { label: '社交', path: '/social', icon: Users },
  { label: '设置', path: '/settings', icon: Settings },
]

const isActive = (path: string) => route.path === path

const navigate = (path: string) => {
  router.push(path)
}
</script>

// src/components/game/SideMenu.tsx
import React from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { Flame, Map, Scroll, Package, ShoppingBag, Trophy, Users, Settings, Home } from 'lucide-react';
import { useUIStore } from '../../store/uiStore';
import { useSocialStore } from '../../store/socialStore';
import { useQuestStore } from '../../store/questStore';

const iconMap: Record<string, React.ReactNode> = {
  Flame: <Flame size={18} />,
  Map: <Map size={18} />,
  Scroll: <Scroll size={18} />,
  Package: <Package size={18} />,
  ShoppingBag: <ShoppingBag size={18} />,
  Trophy: <Trophy size={18} />,
  Users: <Users size={18} />,
  Settings: <Settings size={18} />,
  Home: <Home size={18} />,
};

const navItems = [
  { key: 'lobby', label: '大厅', icon: 'Home', path: '/lobby' },
  { key: 'cultivation', label: '修炼', icon: 'Flame', path: '/cultivation' },
  { key: 'explore', label: '探索', icon: 'Map', path: '/explore' },
  { key: 'quests', label: '任务', icon: 'Scroll', path: '/quests' },
  { key: 'inventory', label: '背包', icon: 'Package', path: '/inventory' },
  { key: 'shop', label: '坊市', icon: 'ShoppingBag', path: '/shop' },
  { key: 'ranking', label: '排行', icon: 'Trophy', path: '/ranking' },
  { key: 'social', label: '社交', icon: 'Users', path: '/social' },
  { key: 'settings', label: '设置', icon: 'Settings', path: '/settings' },
];

interface SideMenuProps {
  /** 移动端：强制展示 */
  forceOpen?: boolean;
}

const SideMenu: React.FC<SideMenuProps> = ({ forceOpen = false }) => {
  const location = useLocation();
  const setSideMenuOpen = useUIStore((s) => s.setSideMenuOpen);
  const unreadSocial = useSocialStore((s) => s.getUnreadCount());
  const claimableQuests = useQuestStore((s) =>
    s.quests.filter((q) => q.status === 'claimable').length
  );

  const badges: Record<string, number> = {
    social: unreadSocial,
    quests: claimableQuests,
  };

  const handleNavClick = () => {
    setSideMenuOpen(false);
  };

  return (
    <nav
      className={`flex flex-col h-full w-56 shrink-0 py-3 overflow-y-auto ${forceOpen ? '' : 'hidden lg:flex'}`}
      style={{
        background: 'linear-gradient(180deg, rgba(13,17,23,0.98) 0%, rgba(18,22,30,0.95) 100%)',
        borderRight: '1px solid var(--color-border)',
      }}
    >
      {/* 宗门标志 */}
      <div
        className="px-5 pb-4 mb-2"
        style={{ borderBottom: '1px solid var(--color-border)' }}
      >
        <div className="text-center">
          <div className="text-2xl mb-1">⚔️</div>
          <div className="text-xs font-bold tracking-widest text-glow-gold">天道仙途</div>
          <div className="text-xs mt-0.5" style={{ color: 'var(--color-text-muted)' }}>道法自然</div>
        </div>
      </div>

      {/* 导航项 */}
      <div className="flex-1 px-2 space-y-0.5">
        {navItems.map((item) => {
          const isActive = location.pathname === item.path;
          const badge = badges[item.key] ?? 0;

          return (
            <NavLink
              key={item.key}
              to={item.path}
              onClick={handleNavClick}
              className="flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-150 relative group"
              style={{
                background: isActive ? 'linear-gradient(135deg, rgba(212,168,67,0.12), rgba(139,105,20,0.08))' : 'transparent',
                color: isActive ? 'var(--color-gold)' : 'var(--color-text-secondary)',
                border: isActive ? '1px solid rgba(212,168,67,0.2)' : '1px solid transparent',
              }}
            >
              {/* 激活状态左侧装饰条 */}
              {isActive && (
                <div
                  className="absolute left-0 top-1 bottom-1 w-0.5 rounded-full"
                  style={{ background: 'var(--color-gold)' }}
                />
              )}

              <span className={isActive ? '' : 'group-hover:text-[--color-text-primary] transition-colors'}>
                {iconMap[item.icon]}
              </span>
              <span className="text-sm font-medium">{item.label}</span>

              {badge > 0 && (
                <span
                  className="ml-auto flex items-center justify-center rounded-full min-w-[18px] h-[18px] text-white"
                  style={{ background: 'var(--color-vermillion)', fontSize: '10px', padding: '0 4px' }}
                >
                  {badge > 99 ? '99+' : badge}
                </span>
              )}
            </NavLink>
          );
        })}
      </div>

      {/* 底部版本信息 */}
      <div className="px-5 pt-3 mt-2" style={{ borderTop: '1px solid var(--color-border)' }}>
        <div className="text-xs text-center" style={{ color: 'var(--color-text-muted)' }}>
          v1.0.0 · 仙途正道
        </div>
      </div>
    </nav>
  );
};

export default SideMenu;
