// src/components/ui/ConfirmDialog.vue
<template>
  <Modal :model-value="modelValue" :title="title" size="sm" @close="handleCancel">
    <div class="flex items-start gap-4">
      <div
        class="w-12 h-12 rounded-full flex items-center justify-center shrink-0"
        :class="[
          type === 'danger' ? 'bg-red-500/20' : 'bg-yellow-500/20'
        ]"
      >
        <AlertTriangle
          :size="24"
          :class="type === 'danger' ? 'text-red-500' : 'text-yellow-500'"
        />
      </div>
      <div class="flex-1">
        <p class="text-sm" style="color: var(--color-text-primary)">
          {{ message }}
        </p>
        <p v-if="description" class="text-xs mt-2" style="color: var(--color-text-muted)">
          {{ description }}
        </p>
      </div>
    </div>

    <template #footer>
      <Button variant="ghost" @click="handleCancel">{{ cancelText }}</Button>
      <Button :variant="type === 'danger' ? 'danger' : 'gold'" @click="handleConfirm">
        {{ confirmText }}
      </Button>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { AlertTriangle } from 'lucide-vue-next'
import Modal from './Modal.vue'
import Button from './Button.vue'

interface Props {
  modelValue: boolean
  title?: string
  message: string
  description?: string
  confirmText?: string
  cancelText?: string
  type?: 'danger' | 'warning'
}

const props = withDefaults(defineProps<Props>(), {
  title: '确认操作',
  message: '确定要执行此操作吗？',
  description: '',
  confirmText: '确定',
  cancelText: '取消',
  type: 'danger',
})

const emit = defineEmits(['update:modelValue', 'confirm', 'cancel'])

const handleConfirm = () => {
  emit('confirm')
  emit('update:modelValue', false)
}

const handleCancel = () => {
  emit('cancel')
  emit('update:modelValue', false)
}
</script>

// src/components/ui/ConfirmDialog.tsx
import React from 'react';
import Modal from './Modal';
import Button from './Button';
import { AlertTriangle } from 'lucide-react';

interface ConfirmDialogProps {
  open: boolean;
  onConfirm: () => void;
  onCancel: () => void;
  title?: string;
  content?: React.ReactNode;
  confirmText?: string;
  cancelText?: string;
  danger?: boolean;
  loading?: boolean;
}

const ConfirmDialog: React.FC<ConfirmDialogProps> = ({
  open,
  onConfirm,
  onCancel,
  title = '请确认',
  content,
  confirmText = '确认',
  cancelText = '取消',
  danger = false,
  loading = false,
}) => {
  return (
    <Modal
      open={open}
      onClose={onCancel}
      title={
        <div className="flex items-center gap-2">
          <AlertTriangle size={16} style={{ color: danger ? '#f87171' : 'var(--color-gold)' }} />
          {title}
        </div>
      }
      width={380}
      footer={
        <>
          <Button variant="ghost" size="sm" onClick={onCancel} disabled={loading}>
            {cancelText}
          </Button>
          <Button
            variant={danger ? 'danger' : 'gold'}
            size="sm"
            onClick={onConfirm}
            loading={loading}
          >
            {confirmText}
          </Button>
        </>
      }
    >
      <p className="text-sm" style={{ color: 'var(--color-text-primary)' }}>
        {content ?? '此操作不可撤销，道友确认继续？'}
      </p>
    </Modal>
  );
};

export default ConfirmDialog;
