// src/components/ui/Drawer.vue
<template>
  <Teleport to="body">
    <Transition name="drawer">
      <div
        v-if="modelValue"
        class="fixed inset-0 z-50"
        @click.self="handleClose"
      >
        <div class="fixed inset-0 bg-black/50 backdrop-blur-sm" @click="handleClose" />

        <div
          class="fixed bg-[var(--color-ink)] overflow-hidden shadow-2xl flex flex-col"
          :class="[
            positionClasses[position],
            sizeClasses[size]
          ]"
          :style="{ border: '1px solid var(--color-border-gold)' }"
        >
          <div v-if="$slots.header || title" class="px-6 py-4 shrink-0" :style="{ borderBottom: '1px solid var(--color-border)' }">
            <div class="flex items-center justify-between">
              <slot name="header">
                <h3 class="text-lg font-semibold text-glow-gold">{{ title }}</h3>
              </slot>
              <button
                v-if="closable"
                class="p-1 rounded hover:bg-white/10 transition-colors"
                @click="handleClose"
              >
                <X :size="20" style="color: var(--color-text-muted)" />
              </button>
            </div>
          </div>

          <div class="flex-1 overflow-y-auto p-6">
            <slot></slot>
          </div>

          <div v-if="$slots.footer" class="px-6 py-4 shrink-0" :style="{ borderTop: '1px solid var(--color-border)' }">
            <slot name="footer"></slot>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { X } from 'lucide-vue-next'

interface Props {
  modelValue: boolean
  title?: string
  position?: 'left' | 'right' | 'top' | 'bottom'
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full'
  closable?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  title: '',
  position: 'right',
  size: 'md',
  closable: true,
})

const emit = defineEmits(['update:modelValue', 'close'])

const positionClasses = {
  left: 'top-0 left-0 h-full',
  right: 'top-0 right-0 h-full',
  top: 'top-0 left-0 w-full',
  bottom: 'bottom-0 left-0 w-full',
}

const sizeClasses = {
  sm: 'w-64',
  md: 'w-80',
  lg: 'w-96',
  xl: 'w-[500px]',
  full: 'w-full h-full',
}

const handleClose = () => {
  emit('update:modelValue', false)
  emit('close')
}
</script>

<style scoped>
.drawer-enter-active,
.drawer-leave-active {
  transition: all 0.3s ease;
}

.drawer-enter-from,
.drawer-leave-to {
  opacity: 0;
}

.drawer-enter-from > div:last-child,
.drawer-leave-to > div:last-child {
  transform: translateX(100%);
}
</style>

// src/components/ui/Drawer.tsx
import React, { useEffect } from 'react';
import { X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface DrawerProps {
  open: boolean;
  onClose: () => void;
  title?: React.ReactNode;
  children: React.ReactNode;
  width?: number | string;
  placement?: 'left' | 'right';
}

const Drawer: React.FC<DrawerProps> = ({
  open,
  onClose,
  title,
  children,
  width = 320,
  placement = 'right',
}) => {
  useEffect(() => {
    if (open) document.body.style.overflow = 'hidden';
    else document.body.style.overflow = '';
    return () => { document.body.style.overflow = ''; };
  }, [open]);

  return (
    <AnimatePresence>
      {open && (
        <div className="fixed inset-0 z-40 flex">
          {/* 遮罩 */}
          <div
            className="absolute inset-0"
            style={{ backgroundColor: 'rgba(0,0,0,0.6)' }}
            onClick={onClose}
          />
          {/* 抽屉主体 */}
          <motion.div
            initial={{ x: placement === 'right' ? width : -Number(width) }}
            animate={{ x: 0 }}
            exit={{ x: placement === 'right' ? width : -Number(width) }}
            transition={{ duration: 0.25, ease: 'easeOut' }}
            className="relative ml-auto flex flex-col h-full overflow-hidden"
            style={{
              width,
              background: 'var(--color-dark)',
              borderLeft: placement === 'right' ? '1px solid var(--color-border-gold)' : undefined,
              borderRight: placement === 'left' ? '1px solid var(--color-border-gold)' : undefined,
            }}
          >
            <div
              className="flex items-center justify-between px-5 py-4"
              style={{ borderBottom: '1px solid var(--color-border)' }}
            >
              <span className="font-semibold text-glow-gold">{title}</span>
              <button onClick={onClose} className="p-1 hover:bg-white/10 rounded transition-colors">
                <X size={16} style={{ color: 'var(--color-text-secondary)' }} />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-4">{children}</div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};

export default Drawer;
