// src/components/ui/Modal.vue
<template>
  <Teleport to="body">
    <Transition name="modal">
      <div
        v-if="modelValue"
        class="fixed inset-0 z-50 flex items-center justify-center p-4"
        @click.self="handleClose"
      >
        <div class="fixed inset-0 bg-black/60 backdrop-blur-sm" @click="handleClose" />

        <div
          class="relative w-full max-h-[90vh] overflow-hidden rounded-lg"
          :class="[sizeClasses[size]]"
          :style="{ background: 'linear-gradient(145deg, rgba(22,27,34,0.98) 0%, rgba(13,17,23,0.99) 100%)', border: '1px solid var(--color-border-gold)', boxShadow: '0 0 60px rgba(212,168,67,0.2)' }"
        >
          <div v-if="$slots.header || title" class="px-6 py-4" style="border-bottom: 1px solid var(--color-border)">
            <slot name="header">
              <h3 class="text-lg font-semibold text-glow-gold">{{ title }}</h3>
            </slot>
            <button
              v-if="closable"
              class="absolute top-4 right-4 p-1 rounded hover:bg-white/10 transition-colors"
              @click="handleClose"
            >
              <X :size="20" style="color: var(--color-text-muted)" />
            </button>
          </div>

          <div class="px-6 py-4 overflow-y-auto" :style="{ maxHeight: 'calc(90vh - 140px)' }">
            <slot></slot>
          </div>

          <div v-if="$slots.footer" class="px-6 py-4 flex justify-end gap-3" style="border-top: 1px solid var(--color-border)">
            <slot name="footer"></slot>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { watch } from 'vue'
import { X } from 'lucide-vue-next'

interface Props {
  modelValue: boolean
  title?: string
  size?: 'sm' | 'md' | 'lg' | 'xl'
  closable?: boolean
  closeOnEscape?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  title: '',
  size: 'md',
  closable: true,
  closeOnEscape: true,
})

const emit = defineEmits(['update:modelValue', 'close'])

const sizeClasses = {
  sm: 'max-w-sm',
  md: 'max-w-md',
  lg: 'max-w-2xl',
  xl: 'max-w-4xl',
}

const handleClose = () => {
  if (props.closable) {
    emit('update:modelValue', false)
    emit('close')
  }
}

watch(() => props.modelValue, (val) => {
  if (val && props.closeOnEscape) {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') handleClose()
    }
    document.addEventListener('keydown', handleEscape)
    return () => document.removeEventListener('keydown', handleEscape)
  }
})
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: all 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

.modal-enter-from > div:last-child,
.modal-leave-to > div:last-child {
  transform: scale(0.95);
}
</style>

// src/components/ui/Modal.tsx
import React, { useEffect } from 'react';
import { X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title?: React.ReactNode;
  children: React.ReactNode;
  width?: number | string;
  footer?: React.ReactNode;
  closable?: boolean;
}

const Modal: React.FC<ModalProps> = ({
  open,
  onClose,
  title,
  children,
  width = 480,
  footer,
  closable = true,
}) => {
  // 按 ESC 关闭
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && open) onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [open, onClose]);

  return (
    <AnimatePresence>
      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          style={{ backdropFilter: 'blur(4px)', backgroundColor: 'rgba(0,0,0,0.7)' }}
          onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.92, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.92, y: 20 }}
            transition={{ duration: 0.22, ease: 'easeOut' }}
            className="game-card relative flex flex-col"
            style={{ width, maxWidth: '100%', maxHeight: '85vh' }}
          >
            {/* 顶部装饰线 */}
            <div className="divider-gold absolute top-0 left-0 right-0" />

            {/* 头部 */}
            {(title || closable) && (
              <div
                className="flex items-center justify-between px-5 py-4"
                style={{ borderBottom: '1px solid var(--color-border)' }}
              >
                <span className="text-base font-semibold text-glow-gold">{title}</span>
                {closable && (
                  <button
                    onClick={onClose}
                    className="p-1 rounded transition-colors hover:bg-white/10"
                    style={{ color: 'var(--color-text-secondary)' }}
                  >
                    <X size={16} />
                  </button>
                )}
              </div>
            )}

            {/* 内容 */}
            <div className="flex-1 overflow-y-auto p-5">{children}</div>

            {/* 底部 */}
            {footer && (
              <div
                className="flex items-center justify-end gap-3 px-5 py-4"
                style={{ borderTop: '1px solid var(--color-border)' }}
              >
                {footer}
              </div>
            )}
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};

export default Modal;
