// src/components/ui/SearchBar.tsx
import React, { useState } from 'react';
import { Search, X } from 'lucide-react';

interface SearchBarProps {
  value?: string;
  onChange?: (value: string) => void;
  placeholder?: string;
  className?: string;
}

const SearchBar: React.FC<SearchBarProps> = ({
  value,
  onChange,
  placeholder = '搜寻...',
  className = '',
}) => {
  const [internal, setInternal] = useState('');
  const isControlled = value !== undefined;
  const current = isControlled ? value : internal;

  const handleChange = (v: string) => {
    if (!isControlled) setInternal(v);
    onChange?.(v);
  };

  return (
    <div
      className={`flex items-center gap-2 px-3 py-2 rounded-lg ${className}`}
      style={{
        background: 'rgba(0,0,0,0.3)',
        border: '1px solid var(--color-border)',
      }}
    >
      <Search size={14} style={{ color: 'var(--color-text-muted)', flexShrink: 0 }} />
      <input
        className="flex-1 bg-transparent outline-none text-sm"
        style={{ color: 'var(--color-text-primary)', minWidth: 0 }}
        placeholder={placeholder}
        value={current}
        onChange={(e) => handleChange(e.target.value)}
      />
      {current && (
        <button onClick={() => handleChange('')} className="hover:opacity-70 transition-opacity">
          <X size={12} style={{ color: 'var(--color-text-muted)' }} />
        </button>
      )}
    </div>
  );
};

export default SearchBar;

// src/components/ui/SearchBar.vue
<template>
  <div class="relative">
    <div
      class="flex items-center gap-2 px-4 py-2.5 rounded-lg transition-all duration-200"
      :style="{ background: 'rgba(0,0,0,0.3)', border: '1px solid var(--color-border)' }"
      :class="focused ? 'border-[var(--color-gold)]' : ''"
    >
      <Search :size="16" :style="{ color: focused ? 'var(--color-gold)' : 'var(--color-text-muted)', transition: 'color 0.2s' }" />
      <input
        ref="inputRef"
        v-model="model"
        class="flex-1 bg-transparent outline-none text-sm"
        :style="{ color: 'var(--color-text-primary)' }"
        :placeholder="placeholder"
        @focus="focused = true"
        @blur="focused = false"
      />
      <button
        v-if="model"
        class="p-1 rounded hover:bg-white/10 transition-colors"
        @click="clear"
      >
        <X :size="14" style="color: var(--color-text-muted)" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Search, X } from 'lucide-vue-next'

interface Props {
  modelValue?: string
  placeholder?: string
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  placeholder: '搜索...',
})

const emit = defineEmits(['update:modelValue'])

const model = ref(props.modelValue)
const focused = ref(false)
const inputRef = ref<HTMLInputElement | null>(null)

const clear = () => {
  model.value = ''
  emit('update:modelValue', '')
  inputRef.value?.focus()
}
</script>
